### ISSUE TITLE
Assertion failed: r1.o != NULL, file exec.c, line 889

### ISSUE THREAD

**Issue by lawiet47** [hillu/go-yara#70]
I am scanning files against a large collection of compiled yara rules. I am using `yara-4.0.0`

I am encountering this error when I try to run the cross-compiled version of the same go code on windows OS.

When I scan the same files with the same yara ruleset on linux, everything goes smoothly. I already searched a bit for this issue and I was hoping getting rid of the `hash` import in yara would solve the problem. Unfortunately it did not.

Any idea what might be causing this?

**Comment by hillu** [comment]
This is likely a bug in YARA itself. It might have been fixed in 4.0.1, please do try that. 

Can you share any of the ingredients for reproducing the bug (Go code, ruleset, set of files that trigger the behavior)?

**Comment by lawiet47** [comment]
I've tried to run the same code with the version 4.0.1. Unfortunately I'm still getting the same error. 
The block of code is as simple as this.

func (s* YRScanner) ScanFile(path string) (error) {

	var err error
	var x []yara.MatchRule
	x, err = s.FileSystemRules.ScanFile(path, 0, 0)
	if err != nil {
		return err
	}
	if len(x) > 0 {
		for _, match := range x {
			for id, value := range match.Metas {
				fmt.Printf("[SCANNER] Identifier: %s, Value: %s\n", id, value)
			}
		}
		s.Matches = append(s.Matches, yr_match{x, path})
	}
	
	return err
}

This works perfectly with every compiled rule I have on linux. It also works with some of the rules on windows. But one of my rulesets doesn't seem to work well on windows and cause assertion error

**Comment by lawiet47** [comment]
I should also state that using the `yara64.exe` (v4.0.1) with the exact same ruleset on windows works perfectly without any errors

**Comment by hillu** [comment]
Okay, let's check a few things… Am I assuming correctly that you are not running multiple scans concurrently? Do you have the YARA rules in source form so you could strip out rules that don't contribute to the problem? Have you built YARA for Windows with OpenSSL support? (Since you mentioned the hash module above, I was reminded of the OpenSSL-less hash module code I contributed some years ago.)

**Comment by lawiet47** [comment]
Okay the problem was not with the hash module. I splitted one of my rulesets which was causing the problem into individual yara rules. I noticed that after removing the `pe.signatutes` keyword from the rule, the scan completed without any errors. Now, I've deleted signature check from all of my rules, but something is still giving me the same error. I think it's again something `pe` module related. I'm also checking the magic bytes of the pe file before scanning the file with `pe` module which explains why I'm not getting the erros on linux.
But I still don't understand why the error doesn't show up when `yara64.exe` is used with the same rulesets.

**Comment by lawiet47** [comment]
Is there any way I can get the rule-name that's giving me the error from any of the `func(r* Rules) Scan*` functions?

**Comment by lawiet47** [comment]
Also the error is triggered whenever a valid ".exe", ".dll" or a ".sys" file is scanned.

**Comment by hillu** [comment]
> Is there any way I can get the rule-name that's giving me the error from any of the `func(r* Rules) Scan*` functions?

You could patch YARA, specifically the `yr_execute_code` function by replacing every `assert(CONDITION)` with `if (!CONDITION) { return ERROR_INTERNAL_FATAL_ERROR; }` and then use the`(*Scanner).GetLastErrorRule` and `(*Scanner).GetLastErrorString` methods.

**Comment by hillu** [comment]
Here's another idea for printf-debugging. From the relvant code:
```
        r1.o = yr_object_lookup_field(r1.o, identifier);

        assert(r1.o != NULL);
```
How about logging `identifier`?

**Comment by lawiet47** [comment]
I've tried patching YARA myself by replacing each `assert(CONDITION)` with `if (!CONDITION) { return ERROR_INTERNAL_FATAL_ERROR; }`. But after cross-compiling `libyara` and `go-yara` for windows The `l` in `l := s.Scanner.GetLastErrorRule()` is `nil`.

Maybe I'm doing something wrong while compiling? Are the old compiled files somehow messing with the operation? Is there any other way to clean the folder other than `make clean` ?The instructions I followed are below:

FOR libyara:
`make clean`
`cd ${YARA_SRC} \
  && ./bootstrap.sh \
  && ./configure --host=x86_64-w64-mingw32 --disable-magic --disable-cuckoo --without-crypto --prefix=${YARA_SRC}/x86_64-w64-mingw32 \
  && make -C ${YARA_SRC} \
  && make -C ${YARA_SRC} install`

FOR GO-yara:
`go get -d -u github.com/hillu/go-yara`
`go install github.com/hillu/go-yara`
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 \
  CC=x86_64-w64-mingw32-gcc \
  PKG_CONFIG_PATH=${YARA_SRC}/x86_64-w64-mingw32/lib/pkgconfig \
  go install -ldflags '-extldflags "-static"' github.com/hillu/go-yara`

**Comment by lawiet47** [comment]
Okay seems to me the issue might be because I'm building YARA for windows WITHOUT Openssl support and that seems to disable some of the `pe`'s features. I already installed `libssl-dev` on debian for openSSL support. It didn't work, I think I need to pass the openSSL header files as a parameter when compiling yara for windows. Can you please give a reference on how to do it?

**Comment by hillu** [comment]
> I've tried patching YARA myself by replacing each `assert(CONDITION)` with `if (!CONDITION) { return ERROR_INTERNAL_FATAL_ERROR; }`. I even tried to print out the `identifier`. But after cross-compiling `libyara` and `go-yara` for windows The `l` in `l := s.Scanner.GetLastErrorRule()` is `nil`.

It was worth a try. :-)

Cross-building YARA with OpenSSL support for Windows on Linux is possible but a little more complicated than what I have described in the README. You have to cross-build OpenSSL first and point yara's configure script in the right directions so it finds both headers and the library to link against. [Spyre](https://github.com/DCSO/spyre) contains a bunch of GNU Make to do just that. (As a bonus, you also get a completely static build for Linux systems, thanks to musl-libc.)

In any case, since your issue happens on Windows without OpenSSL, it seems to be related to too-badly-tested code by me. I should really see to getting this fixed.

Are we talking about `pe.imphash` by any chance?

**Comment by hillu** [comment]
>  I even tried to print out the `identifier`

Did you try only putting the `printf` statement and leaving the `assert` alone, like below? There'll probably be more than one line of debug output before `assert` terminates the program, we only need the last two lines.
``` diff
diff --git a/libyara/exec.c b/libyara/exec.c
index 513aa920..49562a74 100644
--- a/libyara/exec.c
+++ b/libyara/exec.c
@@ -880,15 +880,20 @@ int yr_execute_code(
       case OP_OBJ_FIELD:
         identifier = *(char**)(ip);
         ip += sizeof(uint64_t);
 
         pop(r1);
         ensure_defined(r1);
 
+        fprintf(stderr, "xxx OP_OBJ_FIELD: identifier: len=%d; '%s'\n", (int)strlen(identifier), identifier);
         r1.o = yr_object_lookup_field(r1.o, identifier);
+        if (r1.o == NULL)
+        {
+          fprintf(stderr, "xxx OP_OBJ_FIELD: Uh-oh: result == NULL\n");
+        }
 
         assert(r1.o != NULL);
         push(r1);
         break;
 
       case OP_OBJ_VALUE:
         pop(r1);
```

**Comment by hillu** [comment]
I noticed that you mentioned `yara64.exe` above with which you could not reproduce the bug. I am assuming that this is the binary provided on the YARA Github page. Those binaries are built using the Visual Studio C compiler and contain OpenSSL.

Have you tried to reproduce the bug with your cross-compiled `yara.exe`?

**Comment by lawiet47** [comment]
> 
> 
> > I even tried to print out the `identifier`
> 
> Did you try only putting the `printf` statement and leaving the `assert` alone, like below? There'll probably be more than one line of debug output before `assert` terminates the program, we only need the last two lines.
> 
> ```diff
> diff --git a/libyara/exec.c b/libyara/exec.c
> index 513aa920..49562a74 100644
> --- a/libyara/exec.c
> +++ b/libyara/exec.c
> @@ -880,15 +880,20 @@ int yr_execute_code(
>        case OP_OBJ_FIELD:
>          identifier = *(char**)(ip);
>          ip += sizeof(uint64_t);
>  
>          pop(r1);
>          ensure_defined(r1);
>  
> +        fprintf(stderr, "xxx OP_OBJ_FIELD: identifier: len=%d; '%s'\n", (int)strlen(identifier), identifier);
>          r1.o = yr_object_lookup_field(r1.o, identifier);
> +        if (r1.o == NULL)
> +        {
> +          fprintf(stderr, "xxx OP_OBJ_FIELD: Uh-oh: result == NULL\n");
> +        }
>  
>          assert(r1.o != NULL);
>          push(r1);
>          break;
>  
>        case OP_OBJ_VALUE:
>          pop(r1);
> ```

Yeah the adding two debug outputs before `assert` helped me to see the problem. It was `pe`'s `number_of_signatures` variable that caused the assertion error. Removing them solved the issue.

**Comment by lawiet47** [comment]
> 
> 
> I noticed that you mentioned `yara64.exe` above with which you could not reproduce the bug. I am assuming that this is the binary provided on the YARA Github page. Those binaries are built using the Visual Studio C compiler and contain OpenSSL.
> 
> Have you tried to reproduce the bug with your cross-compiled `yara.exe`?

Interestingly enough, after cross compiling libyara for windows, `yara.exe` doesn't seem to do anything when executed. No help option is displayed nor any parameters are accepted. I am clearly not cross compiling `libyara` correctly and I don't wanna spend time reversing `yara.exe` to see what's wrong. Is there might be any reason why it would be like that even though I'm doing everything according to documentation.

**Comment by lawiet47** [comment]
> 
> 
> > I've tried patching YARA myself by replacing each `assert(CONDITION)` with `if (!CONDITION) { return ERROR_INTERNAL_FATAL_ERROR; }`. I even tried to print out the `identifier`. But after cross-compiling `libyara` and `go-yara` for windows The `l` in `l := s.Scanner.GetLastErrorRule()` is `nil`.
> 
> It was worth a try. :-)
> 
> Cross-building YARA with OpenSSL support for Windows on Linux is possible but a little more complicated than what I have described in the README. You have to cross-build OpenSSL first and point yara's configure script in the right directions so it finds both headers and the library to link against. [Spyre](https://github.com/DCSO/spyre) contains a bunch of GNU Make to do just that. (As a bonus, you also get a completely static build for Linux systems, thanks to musl-libc.)
> 
> In any case, since your issue happens on Windows without OpenSSL, it seems to be related to too-badly-tested code by me. I should really see to getting this fixed.
> 
> Are we talking about `pe.imphash` by any chance?

So I guess in order to use the full functionality of the `pe` module (which a lot of my rules depend on) I'll have to dig into `https://github.com/DCSO/spyre` 's code and see how can I cross compile openssl for windows?

**Comment by hillu** [comment]
> Interestingly enough, after cross compiling libyara for windows, `yara.exe` doesn't seem to do anything when executed.

Use `.libs/yara.exe` and `.libs/yarac.exe` from the top build directory. `$top_builddir/yara.exe` and `$top_builddir/yarac.exe` are the equivalents to the shell script that are generated on Unix systems.

**Comment by hillu** [comment]
> So I guess in order to use the full functionality of the `pe` module (which a lot of my rules depend on) I'll have to dig into `https://github.com/DCSO/spyre` 's code and see how can I cross compile openssl for windows?

Have a look at `Makefile` and `3rdparty.mk` for inspiration (or just copy stuff). I wrote that stuff, so I should be able to help you if there are problems.

**Comment by hillu** [comment]
It seems that I am able to reproduce your issue with a minimal example. `l/yara` has been configured with OpenSSL, `l-nc/yara` and `w/yara.exe` have been configured without.
```
$ cat t.yac
import "pe"
rule t { condition: pe.number_of_signatures >= 0 }
$ l/yarac t.yar t.yac
$ l-nc/yara -C pe.yac /dev/null 
xxx OP_OBJ_FIELD: identifier: len=20; 'number_of_signatures'
xxx OP_OBJ_FIELD: Uh-oh: result == NULL
yara: ../../libyara/exec.c:894: yr_execute_code: Assertion `r1.o != NULL' failed.
Aborted
$ wine w/yara.exe -C t.yac nul
000d:err:menubuilder:init_xdg error looking up the desktop directory
xxx OP_OBJ_FIELD: identifier: len=20; 'number_of_signatures'
xxx OP_OBJ_FIELD: Uh-oh: result == NULL
Assertion failed!

Program: Z:\home\bengen\p\deb\yara\w\.libs\yara.exe
File: ../../libyara/exec.c, Line 894

Expression: r1.o != NULL

abnormal program termination
```

**Comment by lawiet47** [comment]
Yes that's correct that's the exact error I got. Right now I'm going through the `Makefile` and `3rdparty.mk` to figure out a way to cross compile openssl and link it to `libyara`

**Comment by lawiet47** [comment]
I looked into Spyre's code to see if I can find a way to cross compile `openssl` and `libyara` for windows. I coudn't find a solution.
So I tried to build `Spyre` and link its `openssl` & `libyara` builds into my project but that didn't work either. After many tries I eventually gave up and now I got two questions:
1. When building Spyre it fails with these errors:
`
[+] GOROOT= GOOS=linux GOARCH=amd64 CC=x86_64-linux-musl-gcc
[+] CGO_CFLAGS=-I/root/spyre/_3rdparty/tgt/x86_64-linux-musl/include
[+] CGO_LDFLAGS=-L/root/spyre/_3rdparty/tgt/x86_64-linux-musl/lib -lyara -lcrypto -ldl -pthread
`
`
mkdir -p _build/x86_64-linux-musl
/bin/go build \
        -ldflags '-w -s -linkmode=external -extldflags "-static"' \
        -tags no_pkg_config \
        -o _build/x86_64-linux-musl/spyre github.com/dcso/spyre/cmd/spyre
github.com/dcso/spyre/vendor/github.com/hillu/go-yara
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:136:8: could not determine kind of name for C.META_TYPE_NULL
cgo: 
x86_64-linux-musl-gcc errors for preamble:
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go: In function 'string_matches':
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:81:36: error: macro "yr_string_matches_foreach" requires 3 arguments, but only 2 given
`
`
   81 |  yr_string_matches_foreach(s, match) {
      |                                    ^
In file included from /root/spyre/_3rdparty/tgt/x86_64-linux-musl/include/yara/exec.h:36,
                 from /root/spyre/_3rdparty/tgt/x86_64-linux-musl/include/yara/modules.h:41,
                 from /root/spyre/_3rdparty/tgt/x86_64-linux-musl/include/yara.h:36,
                 from _gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:10:
/root/spyre/_3rdparty/tgt/x86_64-linux-musl/include/yara/rules.h:67: note: macro "yr_string_matches_foreach" defined here
   67 | #define yr_string_matches_foreach(context, string, match) \
      |`
` 
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:81:2: error: 'yr_string_matches_foreach' undeclared (first use in this function)
   81 |  yr_string_matches_foreach(s, match) {
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:81:2: note: each undeclared identifier is reported only once for each function it appears in
_gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:81:27: error: expected ';' before '{' token
   81 |  yr_string_matches_foreach(s, match) {
      |                           ^          ~
      |                           ;`
`make: *** [Makefile:102: _build/x86_64-linux-musl/spyre] Error 2`

However the `_3rdparty/` folder is populated with `lib/` `include/` and `bin/` folders.

2. When I try to compile `go-yara` by passing the contents under the `_3rdparty/` folder. It gives me an error like below:
`/usr/bin/x86_64-w64-mingw32-ld: /root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib//libyara.a(hash.o):hash.c:(.text+0x1605): undefined reference to `MD5_Update'
/usr/bin/x86_64-w64-mingw32-ld: /root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib//libyara.a(hash.o):hash.c:(.text+0x16fb): undefined reference to `MD5_Final'
collect2: error: ld returned 1 exit status`

The command I use to compile `go-yara` is like below:
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1   CC=x86_64-w64-mingw32-gcc  CGO_CFLAGS=-I/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/include/openssl CGO_LDFLAGS=-L/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib/ PKG_CONFIG_PATH=/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib/pkgconfig   go install -ldflags '-extldflags "-static"' github.com/hillu/go-yara`

P.S I also tried to build `libyara` with `openssl` support but again with no luck:
`checking openssl/safestack.h usability... no
checking openssl/safestack.h presence... no
checking for openssl/safestack.h... no
checking for MD5_Init in -lcrypto... yes
checking for MD5_Update in -lcrypto... yes
checking for MD5_Final in -lcrypto... yes
checking for SHA256_Init in -lcrypto... yes
checking for SHA256_Update in -lcrypto... yes
checking for SHA256_Final in -lcrypto... yes
configure: error: please install OpenSSL library`

The command I used to build `libyara` is like below:
`cd ${YARA_SRC}    && ./bootstrap.sh    && ./configure --host=x86_64-w64-mingw32 --disable-magic --disable-cuckoo --with-crypto --prefix=${YARA_SRC}/x86_64-w64-mingw32 CFLAGS=-I/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/include/openssl LDFLAGS=-L/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib/   && make -C ${YARA_SRC}    && make -C ${YARA_SRC} install`

**Comment by hillu** [comment]
>     `In function 'string_matches': _gopath/src/github.com/dcso/spyre/vendor/github.com/hillu/go-yara/rule.go:81:36: error: macro "yr_string_matches_foreach" requires 3 arguments, but only 2 given`

For Spyre, YARA 3 is still used, this error mesage looks like the C compiler has been looking at yara 4 headers you installed.

**Comment by lawiet47** [comment]
Okay I've managed to successfully build spyre with YARA 4.0.0. I've looked around `3rdparty.mk` and noticed that I can build `go-yara` with openssl since `Spyre` already installed and build all the dependencies for me.
So I tried to install go-yara with: `GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CGO_CFLAGS="-I/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/include" CGO_LDFLAGS="-L/root/spyre/_3rdparty/tgt/x86_64-w64-mingw32/lib -lyara -lcrypto -lws2_32 -lgdi32 -lcrypt32" go install -ldflags '-w -s -linkmode=external -extldflags "-static"' -tags no_pkg_config github.com/hillu/go-yara` to which I received: `# github.com/hillu/go-yara
../go/src/github.com/hillu/go-yara/util.go:9:20: undefined: makecbPool`. I'm sorry but I'm so lost in this and I don't seem to understand the concept of cross building openssl and linking it to yara.
