### ISSUE TITLE
quick guid for building go-yara statically is highly need for green hand.

### ISSUE THREAD

**Issue by jekkay** [hillu/go-yara#76]
quick guid for building go-yara statically is highly need for green hand. cry to post   o(╥﹏╥)o  ！

**Comment by hillu** [comment]
I have just pushed a small change to the README. Please have a closer look at https://github.com/hillu/go-yara/blob/master/README.md#static-builds – do you have a specific question that is not addressed there?

**Comment by hillu** [comment]
@jekkay ping?

**Comment by jekkay** [comment]
> I have just pushed a small change to the README. Please have a closer look at https://github.com/hillu/go-yara/blob/master/README.md#static-builds – do you have a specific question that is not addressed there?

I did follow the tags described in `https://github.com/hillu/go-yara/blob/master/README.md#static-builds`, but errors still come out. 

so i use handy repo `https://github.com/Velocidex/go-yara`  instead to solve my problem.

**Comment by hillu** [comment]
Sorry. Without knowing what errors you are getting I can't help you or improve the documentation. Closing the issue. If you would like to use this repository instead of the Velocidex fork and if you have some error messages to share, please feel free to re-open.
